 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();
var moment = require('moment');

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });
  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    });

app.route("/:dateString").get(function(req, res){
  
  var dateInput = req.params.dateString.trim();
  
  var unixTimeStamp = null;
  var naturalDateString= null;
  if(!isNaN(dateInput)){
    unixTimeStamp = parseInt(dateInput);
    if(new Date(unixTimeStamp).getTime() > 0 ){
      var dateMoment = moment.unix(unixTimeStamp);
      naturalDateString = dateMoment.format("MMMM D, YYYY");
    } else {
      var dateMoment = moment("1970-01-01");
      naturalDateString = dateMoment.format("MMMM D, YYYY");
    }
      
  } else {
    var dateMoment = moment(dateInput);
    naturalDateString = dateMoment.format("MMMM D, YYYY");
    unixTimeStamp = dateMoment.unix();
  }
  
  res.json({"unix" : unixTimeStamp, "natural": naturalDateString});
  
});

// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

